# Generated by Django 2.2.6 on 2019-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hkforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
